spring:
  application:
    name: buzznote-notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

server:
  port: 8082
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.:
      buzznote: DEBUG
