spring:
  application:
    name: buzznote-notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

#  mail:
#    host: ${MAIL_HOST}
#    port: 587
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#        starttls:
#          enable: true

server:
  port: 8082
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.:
      buzznote: DEBUG
