CREATE TABLE IF NOT EXISTS messages (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    message varchar(255),
    receiver varchar(255),
    sender varchar(255),
    CONSTRAINT messages_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    body varchar(200),
    title varchar(255),
    CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
